### ISSUE TITLE
Set X-Frame-Options to SAMEORIGIN

### ISSUE THREAD

**Issue by fjordaan** [isotoma/htmlhub#6]
Currently when embedding an SVG using `object` causes this error in Firefox: 

> Load denied by X-Frame-Options: https://html-templates.isotoma.com/isotoma/thekey/master/img/benefits-icon-clock-path-white.svg does not permit framing.

and in Chrome:

> Refused to display 'https://html-templates.isotoma.com/isotoma/thekey/master/img/benefits-icon-budget-path-white.svg' in a frame because it set 'X-Frame-Options' to 'DENY'.

You can see it on this page: https://html-templates.isotoma.com/isotoma/thekey/master/home-loggedout-sl.html. (Animated SVG icons are supposed to appear under the "Why use The Key?" heading.)

The issue and its solution is described here: https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options and requires the server to be configured to send the right `X-Frame-Options` header. I think we want SAMEORIGIN.

**Comment by winjer** [comment]
Resolved with 5b2b4034013b051bd4bb89d42c525be3a48946b4
